/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guzenkov.sbertask;

import java.lang.reflect.*;
import java.lang.annotation.*;

public class App {
    public static void main(String[] args) {
        // extracted(app);
        SomeClass someClass = SomeClass.getInstance();
        System.out.println("Init");
        System.out.println(someClass);
        someClass.setFileForRefresh("src/main/resources/oneobject.properties");
        someClass.doRefresh();
        System.out.println("Refresh to default");
        System.out.println(someClass);
        someClass.setFileForRefresh("src/main/resources/SomeClass.properties");
        someClass.doRefresh();
        System.out.println("Refresh from file");
        System.out.println(someClass);
    }
}